declare const TERMS: {
    llm: string[][];
    token: string[][];
    tok: string[][];
    tokPerSec: string[][];
    api: string[][];
    apiKey: string[][];
    fullAccess: string[][];
    agent: string[][];
    agentLabel: string[][];
    modelId: string[][];
    providerId: string[][];
    surface: string[][];
    skill: string[][];
    shell: string[][];
    skills: string[][];
    preset: string[][];
    bash: string[][];
    strReplaceEditor: string[][];
    codeModeSdk: string[][];
    ptc: string[][];
    planMode: string[][];
    defaultLabel: string[][];
    cordisStatus: string[][];
    trajDuration: string[][];
    trajUseActualDuration: string[][];
    trajUseEqualWidth: string[][];
    trajTurns: string[][];
    trajExpandTurns: string[][];
    trajCollapseTurns: string[][];
    trajCalls: string[][];
    trajExpandCalls: string[][];
    trajCollapseCalls: string[][];
    session: string[][];
};
export { TERMS };
